// <auto-generated />
using System;
using ManageMenu.DBContext.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuManagement.DBContext.Migrations
{
    [DbContext(typeof(MenuDBContext))]
    partial class MenuDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ManageMenu.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("RootId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("ManageMenu.Entities.Menu", b =>
                {
                    b.HasOne("ManageMenu.Entities.Menu", "Root")
                        .WithMany()
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Root");
                });
#pragma warning restore 612, 618
        }
    }
}
